### ISSUE TITLE
Adding a footer

### ISSUE THREAD

**Issue by rahulpoonia29** [Sejal99/blogging-site#10]
Adding a minimal footer to the website

**Comment by rpunia29** [comment]
@Sejal99  Can you assign the issue under GSSoC'24

**Comment by dhyaneshsiddhartha15** [comment]
I would like to work on adding a footer to the project that will relate to your Blogging Website. Could you please assign this issue to me under GSSoc'24? Looking forward to contributing!"

**Comment by drick-infinity** [comment]
can you assign to me there is footer ready for tailwind css
