### ISSUE TITLE
Enhancing the Header 

### ISSUE THREAD

**Issue by Divyanshi1002** [Sejal99/blogging-site#14]
The website should include a header to facilitate smooth navigation. This header must prominently feature a 'Home' button for easy access to the main page.

**Comment by Priyanka-Ray-Choudhury** [comment]
Hi @Sejal99, I'd like to tackle the [Bug]: Enhancing the Header task. Please assign it to me with the GSSOC tag. I'm an experienced web content writer with a strong background in UI/UX. I've developed numerous websites and authored over 30 articles for Asiana Times. Additionally, I've completed several SEO content writing internships.

**Comment by Divyanshi1002** [comment]
Hey @Priyanka-Ray-Choudhury,

I'm really interested in tackling this issue! Since I created this it, I wanted to express my interest first. 
I have experience in frontend development skills , in javascript, CSS, HTML.that might be helpful for this task.

Hi @Sejal99 ,

Just wanted to let you know I'm also interested in this!
