### ISSUE TITLE
improve overall UI/UX of the website

### ISSUE THREAD

**Issue by advtszn** [Sejal99/blogging-site#15]
current UI of the website is not quite eye catching and professional and can be improved significantly by updating the colors and fonts and with the use of UI libraries like shadcn-ui

**Comment by sambitsingha** [comment]
@Sejal99  As changing the overall UI takes time and efforts , so I would like to do this issue along with others for ease of work. Thank you

**Comment by advtszn** [comment]
@Sejal99 kindly assign this issue to respected contributors

**Comment by vanisharma2003** [comment]
I have a decent amount of experience in frontend domain. I want to contribute and help in improving User Interface of this project.

**Comment by Priyanka-Ray-Choudhury** [comment]
Hey @Sejal99  I'm keen on taking on the task of improving the overall UI/UX of the website labeled as [Bug]. With my experience as a seasoned web content writer, I've crafted numerous websites with commendable UI/UX. Notably, I've authored and published over 30 articles on Asiana Times' website and have undertaken various content writing SEO internships. Please assign this task to me with the GSSOC tag. Thanks!
