### ISSUE TITLE
Improve Login Component Optimization

### ISSUE THREAD

**Issue by Debanjannnn** [Sejal99/blogging-site#17]
The current implementation of the Login component can be optimized for better performance and maintainability. This issue aims to address several areas of improvement, including code optimization, error handling, and consistent code formatting. By optimizing the Login component, we can enhance the user experience and ensure cleaner codebase maintenance.

**Comment by Priyanka-Ray-Choudhury** [comment]
Hey @Sejal99, could you assign me the [Bug] : Improve Login Component Optimization task with the GSSOC tag? I'm experienced in web content writing, having developed websites with excellent UI/UX and published over 30 articles on Asiana Times. I've also completed multiple SEO internships. Thanks!
