### ISSUE TITLE
feat:add emial verificication for security

### ISSUE THREAD

**Issue by Sahilll15** [Sejal99/blogging-site#23]
This feature enhancement focuses on implementing email verification for improved security within our MERN application. By incorporating email verification, we can ensure that user accounts are associated with valid email addresses, reducing the risk of unauthorized access and enhancing the overall integrity of our platform. This feature will require users to verify their email addresses upon registration and may also include re-verification for email changes to existing accounts. By integrating email verification into our application flow, we reinforce our commitment to safeguarding user data and maintaining a secure environment.

**Tasks:**
 Develop a mechanism to send verification emails upon user registration.
 Implement a verification endpoint to handle email verification requests.
 Create a user interface component to guide users through the email verification process.
 Update the backend logic to validate email verification tokens and activate user accounts.
 Ensure that the verification process is seamless and user-friendly.
 Test the email verification flow thoroughly across different environments and email providers.
 Provide clear error messages for failed verification attempts.

assign this to me

**Comment by Priyanka-Ray-Choudhury** [comment]
Hi @Sejal99, could you assign me the task of adding email verification for security? I have experience as a web content writer, developing websites with excellent UI/UX, and have published over 30 articles on Asiana Times' website. Additionally, I've completed multiple SEO internships focusing on content writing. Please tag it with GSSOC. Thanks!

**Comment by Sahilll15** [comment]
@Priyanka-Ray-Choudhury assign this to me
