### ISSUE TITLE
[FIX]: The ui of the navbar is not well good

### ISSUE THREAD

**Issue by mohit-bhandari45** [Sejal99/blogging-site#25]
Description:- The ui of the navbar is not good, the signup and signin are not well good.

Steps to reproduce:-
Step1:- Start the app
Step2:- Just see the homepage(Navbar)

Screeenshots:-
![image](https://github.com/Sejal99/blogging-site/assets/151373021/8d67543c-6baf-4b34-a02b-8133cdf48538)

Want to work on this please assign me! under GSSOC and @Sejal99 update the label to gssoc'24

**Comment by dhanushsurendra** [comment]
Hey @Sejal99 could you please assign me this issue under GSSOC'24 label? I can make it look better

**Comment by ISHWARISD** [comment]
I want to work on it..PLease assign it to me @Sejal99
