### ISSUE TITLE
[BUG] : Login Signup page is not responsive

### ISSUE THREAD

**Issue by MitulSonagara** [Sejal99/blogging-site#27]
Your login and signup pages are not so responsive. I will make it responsive. In addition i also have some another ideas for login and signup if you want to merge them. I am providing you the screenshots of that.
![image](https://github.com/Sejal99/blogging-site/assets/95460188/9e5583aa-4d5c-4fa4-a9e7-3e45ff0ea211)
![image](https://github.com/Sejal99/blogging-site/assets/95460188/562b0c97-7669-4c2c-bbba-dc832d6ddbc6)

I am contributing under GSSOC'24. 
@Sejal99  Please let me know how much changes you want in your website and please consider me first for this issue.

**Comment by FatemaBaig** [comment]
I would like to work on this part of project please assign it to me under GSSOC-24.
