### ISSUE TITLE
Responsive sidebar for mobile view

### ISSUE THREAD

**Issue by MitulSonagara** [Sejal99/blogging-site#28]
Current:
In current version of your website navbar is overlapping when screen is for mobile view.

Changes:
I will make it like responsive side drawer for mobile screen so that it will look good.

I am contributing under GSSOC'24.
@Sejal99 please consider me for this issue first because i have already forked your website and analyze all the things. I would like to contribute more for your website there are so many change that can be made. Like add loaders when signin or signup.
Thank you.

**Comment by dhanushsurendra** [comment]
Hey @Sejal99, I will make an amazing side bar for for mobile view for this project. Could you please assign this issue to me under GSSOC'24 label?

**Comment by dhanushsurendra** [comment]
Hey @Sejal99 , I will design an amazing side drawer for mobile. Could you please assign this issue to me under GSSOC'24 label.
