### ISSUE TITLE
singup and singin not working properly

### ISSUE THREAD

**Issue by AbhiDiva96** [Sejal99/blogging-site#34]
@Sejal99 
I am a backend developer, I am very familiar with jwt(JSON web token) and I can build the singUp and singIn page using token authentication.

so pls assign me this issue.

**Comment by vipulshetty** [comment]
Lets use google and facbook for authentication using next auth I am expert in next js assign this feature to me @Sejal99

**Comment by Shridhar2104** [comment]
@Sejal99 we can use ClerkAuth and make the signup and login better, which will also enable google github and many more auth features
