### ISSUE TITLE
Adding a profile page 

### ISSUE THREAD

**Issue by SamarthUrane** [Sejal99/blogging-site#42]
Implement a profile page section within the navbar, allowing users to conveniently access and manage their personal details, including the option to reset their passwords. This enhancement significantly enhances user experience and contributes to overall platform usability. 
Requesting assignment of this task under GSSOC. Thank you.

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
@Sejal99 Mam, I would really like to work on this issue under Gssoc'24, so please assign it to me.
