### ISSUE TITLE
Add Login username on Navigation

### ISSUE THREAD

**Issue by dhruv8433** [Sejal99/blogging-site#48]
@Sejal99 
we can add login user's username for good user-exprience

it just display logout button
![image](https://github.com/Sejal99/blogging-site/assets/114583978/6060a131-a204-46f0-95c8-d1bc60db8a04)

**Comment by GnanariddhikaRavikumar** [comment]
I would like to work on this issue and I ensure that I can fix it. Could you assign me this issue under GSSOC'24
