### ISSUE TITLE
Add Profile Page

### ISSUE THREAD

**Issue by dhruv8433** [Sejal99/blogging-site#49]
@Sejal99 
there is no user profile page
we can add user profile page something like this 
![image](https://github.com/Sejal99/blogging-site/assets/114583978/79835a6e-4d39-48c0-b538-87ed981919c9)

it looks good and give better user-expriement 
i would like to work on that please assign me

**Comment by GnanariddhikaRavikumar** [comment]
I would also like to work on this issue . Please assign me this under GSSOC'24

**Comment by dhruv8433** [comment]
@Sejal99 please chekout this issue and assign me 
i would like to work on this issue
