### ISSUE TITLE
Sign in and Sign up feature not working

### ISSUE THREAD

**Issue by nagamukesh** [Sejal99/blogging-site#53]
I see that one cannot sign in/sign up manually with email and password(not Google Sign in) and I think this is because it is not actually storing or the feature itself is not working
I can fix this issue by storing email and password details in either in a json file or use MongoDB
please assign this issue to me under gssoc 2024
I can fix it

**Comment by GnanariddhikaRavikumar** [comment]
I can add Sign up sign in feature using mail and password . Please assign me this issue under GSSOC'24
