### ISSUE TITLE
Improvement in home page 

### ISSUE THREAD

**Issue by TusharKumar0907** [Sejal99/blogging-site#56]
Two issues that I found :- 

1) The position of navbar is not fixed when we scroll down
2) The get started option is not in the same line

![image](https://github.com/Sejal99/blogging-site/assets/100371860/4f59fb11-a140-4723-b3e4-fd7843d24965)

**Comment by TusharKumar0907** [comment]
Can you please assign this to me under GSSOC 24 tag ?

**Comment by TusharKumar0907** [comment]
Can you please add the GSSOC label

**Comment by hari659tri** [comment]
I want to work on this issue. Please assign me this under GSSOC24 label
