### ISSUE TITLE
Upload button should disabled if no image selected 

### ISSUE THREAD

**Issue by kapilG0** [Sejal99/blogging-site#59]
In create blog I did not select image just upload and message came up pic uploaded which is wrong
![Screenshot_20240516_112840](https://github.com/Sejal99/blogging-site/assets/59639410/697dcfd6-61b7-4278-a74c-fc23d00d147a)

**Comment by kapilG0** [comment]
Hello @Sejal99 please assign this issue to me under gssoc 24

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
@Sejal99 Mam, I would really like to work on this issue, so please assign it to me.
