### ISSUE TITLE
[Feature]: Loading Component for Login/Sign after submit

### ISSUE THREAD

**Issue by Rehan52004** [Sejal99/blogging-site#63]
No loader is showing after submit the signin/signup form.

User experience is very bad

**Comment by Rehan52004** [comment]
I want to work on this under Gssoc'24

**Comment by GnanariddhikaRavikumar** [comment]
I want to work on the issue , I will be able to create loading component. Could You assign me this issue under GSSOC'24

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
I would really like to work on this issue under Gssoc'24, so please assign it to me.
