### ISSUE TITLE
[Bug] Registration Page : Upload Button Problem 

### ISSUE THREAD

**Issue by Tasnuva12** [Sejal99/blogging-site#66]
When  the upload button is pressed in registration page even without uploading the image , it shows message "Profile picture uploaded successfully".

![image](https://github.com/Sejal99/blogging-site/assets/47001609/ad72a5a4-c1e1-4362-b777-130864116207)

**Comment by Tasnuva12** [comment]
I want to assign this to myself.

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
Sir, I would really like to work on this issue, so please assign it to me.
