### ISSUE TITLE
Landing Page ReDesign

### ISSUE THREAD

**Issue by Prithwi32** [Sejal99/blogging-site#9]
As every website needs attractive Landing page inorder to attract more people to our website and website unique, this issue is very much important to be solved asap

**Comment by Prithwi32** [comment]
@Sejal99 Please could you assign me this issue under GSSoC'24

**Comment by ShreyashKathade** [comment]
Can you assign the issue under GSSoC'24

**Comment by Priyanka-Ray-Choudhury** [comment]
Hi @Sejal99, I'm an experienced web content writer with a knack for creating stunning landing pages. I've crafted websites with excellent UI/UX, including landing pages for various clients. Additionally, I've published over 30 articles on Asiana Times and completed numerous SEO internships. Could you assign me the Landing Page ReDesign task under the GSSOC tag? Thanks!
